name: taxo_enhancer
channels:
  - defaults
dependencies:
  - python==3.9
  - numpy==1.24.3
  - pandas==1.5.3
  - pyyaml==6.0
  - pip==23.0.1
  - pip :
    - opentree==1.0.1
    - GitPython==3.1.31
    - compress_json
    